vcms/vcms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(("vcmsapp.urls", "vcmsapp"), namespace="vcmsapp")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vcms/vcmsapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name='login'),
    path('logout', Logout, name='logout'),
    path('register', Register, name='register'),
    path('return', previous_page, name='return'),
    path('customer/<int:customer_id>/Profile', Profile, name='profile-customer'),
    path('staff/<int:staff_id>/Profile', Profile, name='profile-staff'),
    path('customer/<int:customer_id>/change-password', ChangePassword, name='change-password-customer'),
    path('staff/<int:staff_id>/change-password', ChangePassword, name='change-password-staff'),
    path('terminate-account/<int:customer_id>', TerminateAccount, name='terminate-account'),
    path('customer/<int:customer_id>/Notifications', NotificationPage, name='notification-customer'),
    path('staff/<int:staff_id>/Notifications', NotificationPage, name='notification-staff'),
    path('clear-notifications/<int:customer_id>', ClearNotification, name='clear-notification-customer'),
    path('clear-notifications/<int:staff_id>', ClearNotification, name='clear-notification-staff'),
    path('notification-redirect/<int:notification_id>', NotificationRedirect, name='notification-redirect'),
    path('customer/<int:customer_id>/Appointments', CustomerPage, name='customer'),
    path('staff/<int:staff_id>/Appointments', StaffPage, name='staff'),
    path('staff/<int:staff_id>/make-appointment', MakeAppointmentStaff, name='make-appointment-staff'),
    path('medical-notes/<int:appointment_id>', MedicalNotes, name='medical-notes'),
    path('staff/<int:staff_id>/Slots', SlotPage, name='slot'),
    path('staff/<int:staff_id>/view-slot', ViewSlot, name='view-slot'),
    path('staff/<int:staff_id>/view-event', ViewEvent, name='view-event'),
    path('staff/<int:staff_id>/remove-slot/<int:slot_id>', RemoveSlot, name='remove-slot'),
    path('staff/<int:staff_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-staff'),
    path('staff/<int:staff_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-staff'),
    path('accept-reject-changes', AcceptRejectChanges, name='accept-reject-changes'),
    path('customer/<int:customer_id>/make-appointment', MakeAppointmentCustomer, name='make-appointment-customer'),
    path('customer/<int:customer_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-customer'),
    path('customer/<int:customer_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-customer'),
    path('customer/<int:customer_id>/History', HistoryPage, name='history'),
    path('customer/<int:customer_id>/view-history/<int:appointment_id>', ViewHistory, name='view-history'),
    path('customer/<int:customer_id>/Pets', PetPage, name='pet'),
    path('customer/<int:customer_id>/add-pet', AddPet, name='add-pet'),
    path('upload-pet-image/<int:customer_id>', UploadPetImage, name='upload-pet-image'),
    path('remove-pet-image/<int:customer_id>', RemovePetImage, name='remove-pet-image'),
    path('customer/<int:customer_id>/view-pet/<int:pet_id>', ViewPet, name='view-pet'),
    path('delete-pet-image/<int:customer_id>/<int:pet_id>', DeletePetImage, name='delete-pet-image'),
    path('Adopt-a-Pet', AdoptPage, name='adopt'),
    path('Adopt-a-Pet/view-animal/<int:pet_id>', ViewAdopt, name='view-adopt'),
    path('Adopt-a-Pet/register-animal', RegisterAdopt, name='register-adopt'),
    path('upload-adopt-image', UploadAdoptImage, name='upload-adopt-image'),
    path('remove-adopt-image', RemoveAdoptImage, name='remove-adopt-image'),
    path('delete-adopt-image/<int:pet_id>', DeleteAdoptImage, name='delete-adopt-image'),
    path('admin/<int:admin_id>/Staff', AdminPage, name='admin'),
    path('admin/<int:admin_id>/register-staff', RegisterStaff, name='register-staff'),
    path('admin/<int:admin_id>/view-staff/<str:staff_no>', ViewStaff, name='view-staff'),
    path('admin/<int:admin_id>/approve-customer', ApproveCustomer, name='approve-customer'),

    # JS query endpoints
    path('get-slots-staff', get_slots_staff, name='get-slots-staff'),
    path('get-slots-customer', get_slots_customer, name='get-slots-customer'),
    path('get-pets', get_pets, name='get-pets'),
]

vcms/vcmsapp/views.py
from datetime import datetime
import json
import os
import random
import shutil
from urllib.parse import urlparse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core import serializers
from django.db import transaction
from django.db.models import Q
from sequences import *

from .blockchain import Blockchain
from .models import *
from .utils import *

# Create your views here.
def Home(request):
    return render(request, "Home.html")

# Login and Register
def Login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            if user.role == 'Customer' and not user.is_staff: # validate both role and is_staff fields
                customer = Customer.objects.get(user=user)
                if not customer.is_approved:
                    messages.error(request, "Your account has not been approved yet!")
                    return redirect('vcmsapp:login')
                return redirect('vcmsapp:customer', customer_id=customer.id)
            elif user.role == 'Staff' and user.is_staff:
                if user.is_superuser:
                    admin = Staff.objects.get(user=user)
                    return redirect('vcmsapp:admin', admin_id=admin.id)
                else:
                    staff = Staff.objects.get(user=user)
                    return redirect('vcmsapp:staff', staff_id=staff.id)
            else:
                messages.error(request, "User data error!")
                return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid email or password!")
            return redirect('vcmsapp:login')
    return render(request, "Login.html")

def Register(request):
    if request.method == "POST":
        name        = request.POST['name']
        gender      = request.POST['gender']
        dob         = request.POST['dob'] # date type input default format = 'YYYY-MM-dd'
        phone       = request.POST['phone']
        address     = request.POST['address']
        email       = request.POST['email']
        password    = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists!")
            return redirect('vcmsapp:register')
        elif Customer.objects.filter(phone=phone).exists():
            messages.error(request, "Phone number already exists!")
            return redirect('vcmsapp:register')

        new_user = AddEntity(
            request, User, None,
            email=email,
            password=password,
            role=User.Role.C
        )

        AddEntity(
            request, Customer, None,
            user=new_user,
            name=name,
            gender=gender,
            dob=dob,
            phone=phone,
            address=address,
            is_approved=False
        )

        messages.success(request, 'Registration successful! Please wait for email of approval which would be sent to ' + email + '.')
        return redirect('vcmsapp:login')
    return render(request, "Register.html")

def Logout(request):
    logout(request)
    return redirect('vcmsapp:login')

def previous_page(request):
    previous_page = request.session.get('previous_page', None)
    return redirect(previous_page) if previous_page else redirect('vcmsapp:logout')

@login_required
def Profile(request, staff_id=None, customer_id=None): # staff includes admin
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    if staff_id:
        staff = Staff.objects.get(id=staff_id)
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)

    user = request.user

    disallowed_pages = [
        'change-password',
        'Adopt-a-Pet',
        'Profile',
    ]

    referrer = request.META.get('HTTP_REFERER', None)
    if referrer:
        parsed_url = urlparse(referrer)
        if parsed_url.path not in disallowed_pages and parsed_url.path != '/':
            request.session['previous_page'] = referrer

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newRole = request.POST['role']
                
            EditEntity(
                request, Staff, staff.id, None,
                name=newName,
                gender=newGender,
                role=newRole,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-staff', staff_id=staff_id)
        context['staff'] = staff

    elif customer_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newDob = request.POST['dob']
            newPhone = request.POST['phone']
            newAddress = request.POST['address']

            if customer.phone != newPhone and Customer.objects.filter(phone=newPhone).exists():
                messages.error(request, "Phone number already exists!")
                return redirect('vcmsapp:profile-customer', customer_id=customer_id)

            EditEntity(
                request, Customer, customer.id, None,
                name=newName,
                gender=newGender,
                dob=newDob,
                phone=newPhone,
                address=newAddress,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-customer', customer_id=customer_id)
        context['customer'] = customer
    return render(request, "Profile.html", context)

@login_required
def ChangePassword(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        old_password = request.POST['password']
        new_password = request.POST['newPassword']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password changed successfully!")
            return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid current password!")
            return redirect('vcmsapp:change-password-staff', staff_id=staff_id) if staff_id else redirect('vcmsapp:change-password-customer', customer_id=customer_id)

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "ChangePassword.html", context)

@login_required
def TerminateAccount(request, customer_id):
    to_terminate = Customer.objects.get(id=customer_id)
    if request.method == "POST":
        DeleteEntity(
            request, User, to_terminate.user.id, None
        )

        DeleteEntity(
            request, Customer, to_terminate.id, None
        )
        messages.success(request, "Account terminated successfully!")
        return redirect('vcmsapp:logout')

@login_required
def NotificationPage(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    notifications = Notification.objects.filter(user=user)
    if notifications:
        notifications = serialize_and_paginate(
            notifications, 9            
        )
    else:
        notifications = None

    context = {
        'onPage': 'Notifications',
        'pages': notifications
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "Notification.html", context)

def NotificationRedirect(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    modules = {
        'AppointmentBooked': redirect_view_appointment_staff,
        'AppointmentMade': redirect_view_appointment_customer,
        'AppointmentEditedStaff': redirect_view_appointment_staff,
        'AppointmentEditedCustomer': redirect_view_appointment_customer,
        'AppointmentUpcoming': redirect_view_appointment_customer,
    }

    if notification:
        redirect_func = modules.get(notification.module, None)
        if redirect_func:
            return redirect_func(**notification.data)


def ClearNotification(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        notifications = Notification.objects.filter(user=user)
        for notification in notifications:
            DeleteEntity(
                request, Notification, notification.id, None
            )

        if staff_id:
            staff = Staff.objects.get(id=staff_id)
            return redirect('vcmsapp:notification-staff', staff_id=staff.id)
        elif customer_id:
            customer = Customer.objects.get(id=customer_id)
            return redirect('vcmsapp:notification-customer', customer_id=customer.id)

# Staff
@login_required
def StaffPage(request, staff_id):
    user = request.user

vcms/vcmsapp/templates/ChangePassword.html
{% extends 'Base.html' %}

{% block title %}Change Password | {{user.email}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            Change Password
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        {% include 'forms/ChangePasswordForm.html' %}
    </div>
</div>
<div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-3">
        {% if customer %}
            {% url 'vcmsapp:profile-staff' staff_id=staff.id as url %}
        {% elif staff %}    
            {% url 'vcmsapp:profile-staff' staff_id=staff.id as url %}
        {% endif %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
    <div class="col-3">
        <button type="submit" style="border-radius: 10px;" id="submitBtn">Change Password</button>
    </div>
</div>

<script>
    var submitBtn = document.getElementById('submitBtn');
    var form = document.getElementById('addSlotForm');
    
    submitBtn.addEventListener('click', function() {
        if (form.reportValidity()) {
            form.submit();
        }
    });

</script>
{% endblock %}

vcms/vcmsapp/templates/Notification.html
{% extends 'Base.html' %}

{% block title %}Notifications{% endblock %}

{% block content %}
<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                Notifications
            </h1>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            {% include 'components/anchor-button.html' with url='#' text="Clear Notifications" id='clearBtn' modal_toggle=True modal_id='clearModal' %}
        </div>
    </div> 
    <div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-inner">
                    {% for page in pages %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            {% for row in page|slice:":3" %}
                                <div class="row">
                                    {% for data in row %}
                                        <div class="col-md-4">
                                            {% url 'vcmsapp:notification-redirect' notification_id=data.id as url %}
                                            {% if data.is_read %}
                                                {% include 'components/card.html' with header=data.title label=data.content url=url color='red' %}
                                            {% else %}
                                                {% include 'components/card.html' with header=data.title label=data.content url=url color='green' %}
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                    {% empty %}
                        <div class="col-md-12" style="text-align: center;">
                            <p>No notifications. Don't worry, you are not having a poor internet connection :></p>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="clearModal" tabindex="-1" aria-labelledby="clearModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="clearModalLabel">Clear Notification</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Are you sure to clear all notifications?</h4>
            </div>
            <div class="modal-footer">
                <div class="row" style="width: 100%;">
                    <div style="display: flex; justify-content: center;">
                        <div class="col-5 mx-2">
                            {% include 'components/anchor-button.html' with url='#' text='Back' modal_dismiss=True %}
                        </div>
                        <div class="col-5 mx-2">
                            <form action="{% if customer %}{% url 'vcmsapp:clear-notification-customer' customer_id=customer.id as url %}{% elif staff %}{% url 'vcmsapp:clear-notification-staff' staff_id=staff.id as url %}{% endif %}" method="post" id="clearForm">
                                {% csrf_token %}
                                {% include 'components/input.html' with type='hidden' id='customer_id' name='customer_id' value=customer.id %}
                                {% include 'components/anchor-button.html' with url='#' text='Clear' id='clearNotificationBtn' %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var clearBtn = document.getElementById('clearNotificationBtn');
    var form = document.getElementById('clearForm');

    if (clearBtn) {
        clearBtn.addEventListener('click', function() {
            if (form.reportValidity()) {
                form.submit();
            }
        });
    }
</script>
{% endblock %}

vcms/vcmsapp/templates/ViewAdopt.html
{% extends 'Base.html' %}

{% block title %}View Animal{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            {{pet.name}}
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="form-container">
            {% include 'details/ViewAdoptDetails.html' %}
            {% if image %}
                {% url 'vcmsapp:delete-adopt-image' pet_id=pet.id as url %}
                {% include 'components/img.html' with image_url=image delete_url=url disabled=True %}
            {% else %}
                {% url 'vcmsapp:upload-adopt-image' as upload_url %}
                {% url 'vcmsapp:remove-adopt-image' as remove_url %}
                {% include 'components/dropzone.html' with upload_url=upload_url remove_url=remove_url disabled=True image_for=pet.name %}
            {% endif %}
        </div>
    </div>
</div>
{% if staff %}
    {% url 'vcmsapp:adopt' as url %}
    {% include 'components/edit-detail-buttons.html' with form_id='editAdoptForm' url=url %}
{% elif customer %}
<div class="row pb-3" style="display: flex; align-items: center; justify-content: center; margin-left: auto;">
    <div class="col-4">
        {% url 'vcmsapp:adopt' as url %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
</div>
{% endif %}
{% endblock %}

vcms/vcmsapp/templates/ViewAppointment.html
{% extends 'Base.html' %}

{% block title %}View Appointment | {{appointment.pet}} at {{appointment.time}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto; display: flex;">
        <div class="col-8">
            <h1 style="font-weight: bold;">
                Appointment at {{appointment.start_time}} for {{appointment.pet}}
            </h1>
        </div>
        <div class="col-1 position-relative">
            {% if change_request %}
                {% include 'components/icon-button.html' with anchor=True url='#' icon='fa fa-bullhorn' title='Change Request' modal=True modal_id='changesModal' color='red' %}
            {% else %}
                {% include 'components/icon-button.html' with anchor=True url='#' icon='fa fa-bullhorn' title='Change Request' modal=True modal_id='changesModal' %}
            {% endif %}
        </div>
        <div class="col-3">
            {% if user.role == 'Staff' %}
                {% if appointment.is_today %}
                    {% if not has_medical_notes %}
                        {% url 'vcmsapp:medical-notes' appointment_id=appointment.id as url %}
                        {% include 'components/anchor-button.html' with url=url text='Medical Notes' %}
                    {% endif %}
                {% endif %}
            {% else %}
                {% include 'components/anchor-button.html' with url='#' text="Cancel Appointment" id='deleteBtn' modal_toggle=True modal_id='cancelModal' %}
            {% endif %}
        </div>
    </div>
    <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        {% if user.role == 'Customer' %}
            {% include 'details/ViewAppointmentDetails.html' with detail='customer' %}
        {% elif user.role == 'Staff' %}
            {% include 'details/ViewAppointmentDetails.html' with detail='staff' %}
        {% endif %}
    </div>
</div>
{% if user.role == 'Customer' %}
    {% url 'vcmsapp:customer' customer_id=customer.id as url %}
    {% include 'components/edit-detail-buttons.html' with form_id='editAppointmentForm' url=url exclude_fields='dateDiv,timeDiv,staffNameDiv,typeDiv' %}
{% elif user.role == 'Staff' %}
    {% url 'vcmsapp:staff' staff_id=staff.id as url %}
    {% include 'components/edit-detail-buttons.html' with form_id='editAppointmentForm' url=url exclude_fields='dateDiv,timeDiv,customerNameDiv,typeDiv' %}
{% endif %}

<!-- Modal -->
<div class="modal fade" id="cancelModal" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="cancelModalLabel">Cancel Confirmation</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Are you sure to cancel?</h4>
            </div>
            <div class="modal-footer">
                <div class="row" style="width: 100%;">
                    <div style="display: flex; justify-content: center;">
                        <div class="col-5 mx-2">
                            {% include 'components/anchor-button.html' with url='#' text='Back' modal_dismiss=True %}
                        </div>
                        <div class="col-5 mx-2">
                            <form action="{% if user.role == 'Staff' %}{% url 'vcmsapp:cancel-appointment-staff' staff_id=staff.id %}{% elif user.role == 'Customer' %}{% url 'vcmsapp:cancel-appointment-customer' customer_id=customer.id %}{% endif %}" method="post" id="cancelAppointmentForm">
                                {% csrf_token %}
                                {% include 'components/input.html' with type='hidden' id='appointment_id' name='appointment_id' value=appointment.id %}
                                {% include 'components/anchor-button.html' with url='#' text='Cancel Appointment' id='cancelAppointmentBtn' %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if attributes %}
<div class="modal fade" id="changesModal" tabindex="-1" aria-labelledby="changesModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="changesModalLabel">Changes</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for key, value in attributes.items %}
                    {% if value.0 != value.1 %}
                        <div class="row">
                            <div class="col-4">
                                <h4>{{key}}</h4>
                            </div>
                            <div class="col-8">
                                <h4>{{value.0}} -> {{value.1}}</h4>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="modal-footer">
                <div class="row" style="width: 100%;">
                    <div style="display: flex; justify-content: center;">
                        <div class="col-3 mx-2">
                            {% include 'components/anchor-button.html' with url='#' text='Back' modal_dismiss=True %}
                        </div>
                        <div class="col-3 mx-2">
                            <form action="{% url 'vcmsapp:accept-reject-changes' %}" method="post" id="rejectChangesForm">
                                {% csrf_token %}
                                {% include 'components/input.html' with type='hidden' id='appointment_id' name='appointment_id' value=appointment.id %}
                                {% include 'components/input.html' with type='hidden' id='decision' name='decision' value='reject' %}
                                {% include 'components/anchor-button.html' with url='#' text='Reject Changes' id='rejectChangesBtn' %}
                            </form>
                        </div>
                        <div class="col-3 mx-2">
                            <form action="{% url 'vcmsapp:accept-reject-changes' %}" method="post" id="acceptChangesForm">
                                {% csrf_token %}
                                {% include 'components/input.html' with type='hidden' id='appointment_id' name='appointment_id' value=appointment.id %}
                                {% include 'components/input.html' with type='hidden' id='decision' name='decision' value='accept' %}
                                {% include 'components/anchor-button.html' with url='#' text='Accept Changes' id='acceptChangesBtn' %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<script>
    var cancelAppointmentBtn = document.getElementById('cancelAppointmentBtn');
    var acceptChangesBtn = document.getElementById('acceptChangesBtn');
    var rejectChangesBtn = document.getElementById('rejectChangesBtn');

    cancelAppointmentBtn.addEventListener('click', function() {
        var cancelAppointmentForm = document.getElementById('cancelAppointmentForm');
        if (cancelAppointmentForm.reportValidity()) {
            cancelAppointmentForm.submit();
        }
    });

    if (acceptChangesBtn) {
        acceptChangesBtn.addEventListener('click', function() {
            var acceptChangesForm = document.getElementById('acceptChangesForm');
            if (acceptChangesForm.reportValidity()) {
                acceptChangesForm.submit();
            }
        });
    }

    if (rejectChangesBtn) {
        rejectChangesBtn.addEventListener('click', function() {
            var rejectChangesForm = document.getElementById('rejectChangesForm');
            if (rejectChangesForm.reportValidity()) {
                rejectChangesForm.submit();
            }
        });
    }
</script>
{% endblock %}