vcms/vcms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(("vcmsapp.urls", "vcmsapp"), namespace="vcmsapp")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vcms/vcmsapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name='login'),
    path('logout', Logout, name='logout'),
    path('register', Register, name='register'),
    path('return', previous_page, name='return'),
    path('customer/<int:customer_id>/Profile', Profile, name='profile-customer'),
    path('staff/<int:staff_id>/Profile', Profile, name='profile-staff'),
    path('customer/<int:customer_id>/change-password', ChangePassword, name='change-password-customer'),
    path('staff/<int:staff_id>/change-password', ChangePassword, name='change-password-staff'),
    path('terminate-account/<int:customer_id>', TerminateAccount, name='terminate-account'),
    path('customer/<int:customer_id>/Notifications', NotificationPage, name='notification-customer'),
    path('staff/<int:staff_id>/Notifications', NotificationPage, name='notification-staff'),
    path('clear-notifications/<int:customer_id>', ClearNotification, name='clear-notification-customer'),
    path('clear-notifications/<int:staff_id>', ClearNotification, name='clear-notification-staff'),
    path('notification-redirect/<int:notification_id>', NotificationRedirect, name='notification-redirect'),
    path('customer/<int:customer_id>/Appointments', CustomerPage, name='customer'),
    path('staff/<int:staff_id>/Appointments', StaffPage, name='staff'),
    path('staff/<int:staff_id>/make-appointment', MakeAppointmentStaff, name='make-appointment-staff'),
    path('medical-notes/<int:appointment_id>', MedicalNotes, name='medical-notes'),
    path('staff/<int:staff_id>/Slots', SlotPage, name='slot'),
    path('staff/<int:staff_id>/view-slot', ViewSlot, name='view-slot'),
    path('staff/<int:staff_id>/view-event', ViewEvent, name='view-event'),
    path('staff/<int:staff_id>/remove-slot/<int:slot_id>', RemoveSlot, name='remove-slot'),
    path('staff/<int:staff_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-staff'),
    path('staff/<int:staff_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-staff'),
    path('accept-reject-changes', AcceptRejectChanges, name='accept-reject-changes'),
    path('customer/<int:customer_id>/make-appointment', MakeAppointmentCustomer, name='make-appointment-customer'),
    path('customer/<int:customer_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-customer'),
    path('customer/<int:customer_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-customer'),
    path('customer/<int:customer_id>/History', HistoryPage, name='history'),
    path('customer/<int:customer_id>/view-history/<int:appointment_id>', ViewHistory, name='view-history'),
    path('customer/<int:customer_id>/Pets', PetPage, name='pet'),
    path('customer/<int:customer_id>/add-pet', AddPet, name='add-pet'),
    path('upload-pet-image/<int:customer_id>', UploadPetImage, name='upload-pet-image'),
    path('remove-pet-image/<int:customer_id>', RemovePetImage, name='remove-pet-image'),
    path('customer/<int:customer_id>/view-pet/<int:pet_id>', ViewPet, name='view-pet'),
    path('delete-pet-image/<int:customer_id>/<int:pet_id>', DeletePetImage, name='delete-pet-image'),
    path('Adopt-a-Pet', AdoptPage, name='adopt'),
    path('Adopt-a-Pet/view-animal/<int:pet_id>', ViewAdopt, name='view-adopt'),
    path('Adopt-a-Pet/register-animal', RegisterAdopt, name='register-adopt'),
    path('upload-adopt-image', UploadAdoptImage, name='upload-adopt-image'),
    path('remove-adopt-image', RemoveAdoptImage, name='remove-adopt-image'),
    path('delete-adopt-image/<int:pet_id>', DeleteAdoptImage, name='delete-adopt-image'),
    path('admin/<int:admin_id>/Staff', AdminPage, name='admin'),
    path('admin/<int:admin_id>/register-staff', RegisterStaff, name='register-staff'),
    path('admin/<int:admin_id>/view-staff/<str:staff_no>', ViewStaff, name='view-staff'),
    path('admin/<int:admin_id>/approve-customer', ApproveCustomer, name='approve-customer'),

    # JS query endpoints
    path('get-slots-staff', get_slots_staff, name='get-slots-staff'),
    path('get-slots-customer', get_slots_customer, name='get-slots-customer'),
    path('get-pets', get_pets, name='get-pets'),
]

vcms/vcmsapp/views.py
from datetime import datetime
import json
import os
import random
import shutil
from urllib.parse import urlparse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core import serializers
from django.db import transaction
from django.db.models import Q
from sequences import *

from .blockchain import Blockchain
from .models import *
from .utils import *

# Create your views here.
def Home(request):
    return render(request, "Home.html")

# Login and Register
def Login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            if user.role == 'Customer' and not user.is_staff: # validate both role and is_staff fields
                customer = Customer.objects.get(user=user)
                if not customer.is_approved:
                    messages.error(request, "Your account has not been approved yet!")
                    return redirect('vcmsapp:login')
                return redirect('vcmsapp:customer', customer_id=customer.id)
            elif user.role == 'Staff' and user.is_staff:
                if user.is_superuser:
                    admin = Staff.objects.get(user=user)
                    return redirect('vcmsapp:admin', admin_id=admin.id)
                else:
                    staff = Staff.objects.get(user=user)
                    return redirect('vcmsapp:staff', staff_id=staff.id)
            else:
                messages.error(request, "User data error!")
                return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid email or password!")
            return redirect('vcmsapp:login')
    return render(request, "Login.html")

def Register(request):
    if request.method == "POST":
        name        = request.POST['name']
        gender      = request.POST['gender']
        dob         = request.POST['dob'] # date type input default format = 'YYYY-MM-dd'
        phone       = request.POST['phone']
        address     = request.POST['address']
        email       = request.POST['email']
        password    = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists!")
            return redirect('vcmsapp:register')
        elif Customer.objects.filter(phone=phone).exists():
            messages.error(request, "Phone number already exists!")
            return redirect('vcmsapp:register')

        new_user = AddEntity(
            request, User, None,
            email=email,
            password=password,
            role=User.Role.C
        )

        AddEntity(
            request, Customer, None,
            user=new_user,
            name=name,
            gender=gender,
            dob=dob,
            phone=phone,
            address=address,
            is_approved=False
        )

        messages.success(request, 'Registration successful! Please wait for email of approval which would be sent to ' + email + '.')
        return redirect('vcmsapp:login')
    return render(request, "Register.html")

def Logout(request):
    logout(request)
    return redirect('vcmsapp:login')

def previous_page(request):
    previous_page = request.session.get('previous_page', None)
    return redirect(previous_page) if previous_page else redirect('vcmsapp:logout')

@login_required
def Profile(request, staff_id=None, customer_id=None): # staff includes admin
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    if staff_id:
        staff = Staff.objects.get(id=staff_id)
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)

    user = request.user

    disallowed_pages = [
        'change-password',
        'Adopt-a-Pet',
        'Profile',
    ]

    referrer = request.META.get('HTTP_REFERER', None)
    if referrer:
        parsed_url = urlparse(referrer)
        if parsed_url.path not in disallowed_pages and parsed_url.path != '/':
            request.session['previous_page'] = referrer

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newRole = request.POST['role']
                
            EditEntity(
                request, Staff, staff.id, None,
                name=newName,
                gender=newGender,
                role=newRole,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-staff', staff_id=staff_id)
        context['staff'] = staff

    elif customer_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newDob = request.POST['dob']
            newPhone = request.POST['phone']
            newAddress = request.POST['address']

            if customer.phone != newPhone and Customer.objects.filter(phone=newPhone).exists():
                messages.error(request, "Phone number already exists!")
                return redirect('vcmsapp:profile-customer', customer_id=customer_id)

            EditEntity(
                request, Customer, customer.id, None,
                name=newName,
                gender=newGender,
                dob=newDob,
                phone=newPhone,
                address=newAddress,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-customer', customer_id=customer_id)
        context['customer'] = customer
    return render(request, "Profile.html", context)

@login_required
def ChangePassword(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        old_password = request.POST['password']
        new_password = request.POST['newPassword']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password changed successfully!")
            return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid current password!")
            return redirect('vcmsapp:change-password-staff', staff_id=staff_id) if staff_id else redirect('vcmsapp:change-password-customer', customer_id=customer_id)

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "ChangePassword.html", context)

@login_required
def TerminateAccount(request, customer_id):
    to_terminate = Customer.objects.get(id=customer_id)
    if request.method == "POST":
        DeleteEntity(
            request, User, to_terminate.user.id, None
        )

        DeleteEntity(
            request, Customer, to_terminate.id, None
        )
        messages.success(request, "Account terminated successfully!")
        return redirect('vcmsapp:logout')

@login_required
def NotificationPage(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    notifications = Notification.objects.filter(user=user)
    if notifications:
        notifications = serialize_and_paginate(
            notifications, 9            
        )
    else:
        notifications = None

    context = {
        'onPage': 'Notifications',
        'pages': notifications
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "Notification.html", context)

def NotificationRedirect(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    modules = {
        'AppointmentBooked': redirect_view_appointment_staff,
        'AppointmentMade': redirect_view_appointment_customer,
        'AppointmentEditedStaff': redirect_view_appointment_staff,
        'AppointmentEditedCustomer': redirect_view_appointment_customer,
        'AppointmentUpcoming': redirect_view_appointment_customer,
    }

    if notification:
        redirect_func = modules.get(notification.module, None)
        if redirect_func:
            return redirect_func(**notification.data)


def ClearNotification(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        notifications = Notification.objects.filter(user=user)
        for notification in notifications:
            DeleteEntity(
                request, Notification, notification.id, None
            )

        if staff_id:
            staff = Staff.objects.get(id=staff_id)
            return redirect('vcmsapp:notification-staff', staff_id=staff.id)
        elif customer_id:
            customer = Customer.objects.get(id=customer_id)
            return redirect('vcmsapp:notification-customer', customer_id=customer.id)

# Staff
@login_required
def StaffPage(request, staff_id):
    user = request.user

vcms/vcmsapp/templates/customer/AddPet.html
{% extends 'Base.html' %}

{% block title %}Add Pet{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            Add Pet
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="form-container">
            {% include 'forms/AddPetForm.html' %}
            <br>
            <div class="row">
                <div class="col-1"></div>
                <div class="col-10">
                    <div class="accordion" id="imageUploadAccordion">
                        <div class="card" style="border-color: #E5E5E5;">
                            <div class="card-header" id="imageUploadHeading" style="background-color: #E5E5E5; border-color: transparent;">
                                {% include 'components/input.html' with type='button' value='Upload Pet Image' accordion_id='imageUploadDiv' icon='fa fa-upload' %}
                            </div>
                            <div class="collapse" id="imageUploadDiv" aria-labelledby="imageUploadHeading" data-bs-parent="#imageUploadAccordion">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data" class="dropzone needsclick" id="imageUpload">
                                        {% csrf_token %}
                                        <div class="dz-message needsclick">
                                            <i class="fa fa-upload"></i>
                                            <h6 style="font-size: smaller;">Drop files here or click to upload.</h6>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row pb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-3">
        {% url 'vcmsapp:pet' customer_id=customer.id as url %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
    <div class="col-3">
        <button type="submit" style="border-radius: 10px;" id="submitBtn">Add Pet</button>
    </div>
</div>
<script>
    Dropzone.autoDiscover = false;

    var imageUpload = new Dropzone("#imageUpload", {
        url: "{% url 'vcmsapp:upload-pet-image' customer_id=customer.id %}",
        paramName: "imageUpload",
        maxFilesize: 2,
        maxFiles: 1,
        acceptedFiles: ".jpeg,.jpg,.png,.gif",
        addRemoveLinks: true,
        uploadMultiple: false,
        dictRemoveFile: "Remove",
        dictFileTooBig: "Image is larger than 2MB",
        dictMaxFilesExceeded: "Only 1 image is allowed",
        init: function() {
            this.on("success", function(file, response) {
                document.getElementById('filename').value = response.filename;
            });
            this.on("addedfile", function(file) {
                if (this.files.length > 1) {
                    this.removeFile(this.files[0]);
                }
            });
            this.on("removedfile", function(file) {
                $.ajax({
                    url: "{% url 'vcmsapp:remove-pet-image' customer_id=customer.id %}",
                    type: "POST",
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        filename: file.name
                    },
                    success: function(response) {
                        toastr.success('Image removed successfully');
                    },
                    error: function(response) {
                        toastr.error('Image failed to remove');
                    }
                })

                if (this.files.length === 0) {
                    this.emit("reset");
                }
            });
            this.on("maxfilesexceeded", function(file) {
                this.removeAllFiles();
                this.addFile(file);
            });
        }
    });

    $(document).ready(function(){
        $(".card").hover(
            function(){
                $(this).find('.collapse').collapse('show');
            },
            function(){
                $(this).find('.collapse').collapse('hide');
            }
        )
    })

    var submitBtn = document.getElementById('submitBtn');
    var form = document.getElementById('addPetForm');

    submitBtn.addEventListener('click', function() {
        if (form.checkValidity()) {
            form.submit();
        }
    });
</script>
{% endblock %}

vcms/vcmsapp/templates/customer/Customer.html
{% extends 'Base.html' %}

{% block title %}Upcoming Appointments | {{customer.name}}{% endblock %}

{% block content %}
<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                Upcoming Appointments
            </h1>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            {% url 'vcmsapp:make-appointment-customer' customer_id=customer.id as url %}
            {% include 'components/anchor-button.html' with url=url text="Make Appointment" %}
        </div>
    </div>
    {% if query %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" query=query %}
    {% else %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" %}
    {% endif %}    
    <div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Pet Name</th>
                    <th>Date & Time</th>
                    <th>Appointment Type</th>
                    <th>Doctor / Groomer</th>
                    <th>View</th>
                </tr>
            </thead>
                {% for page in pages %}
                    <tbody id="body{{page.number}}" {% if page.number != 1 %}hidden{% endif %}>
                        {% for data in page %}
                            <tr style="cursor: pointer;">
                                {% if page.has_previous %}
                                    {% widthratio 10 1 page.previous_page_number as count %}
                                    <td>{{forloop.counter|add:count}}</td>
                                {% else %}
                                    <td>{{forloop.counter}}</td>
                                {% endif %}
                                <td>{{data.pet}}</td>
                                <td>{{data.date}} {{data.time}}</td>
                                <td>{{data.type}}</td>
                                <td>{{data.staff}}</td>
                                <td>
                                    {% url 'vcmsapp:view-appointment-customer' appointment_id=data.id customer_id=customer.id as url %}                                    
                                    {% include 'components/icon-button.html' with anchor=True url=url icon='fa fa-eye' title='View' %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                {% endfor %}
        </table>
        {% include 'components/pagination.html' with pages=pages %}
    </div>
</div>

{% endblock %}

vcms/vcmsapp/templates/customer/History.html
{% extends 'Base.html' %}

{% block title %}History | {{customer.name}}{% endblock %}

{% block content %}
<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                History
            </h1>
        </div>
    </div>
    {% if query %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" query=query %}
    {% else %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" %}
    {% endif %}    
    <div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Pet Name</th>
                    <th>Date & Time</th>
                    <th>Appointment Type</th>
                    <th>Doctor / Groomer</th>
                    <th>Completed</th>
                    <th>View Medical Notes</th>
                </tr>
            </thead>
                {% for page in pages %}
                    <tbody id="body{{page.number}}" {% if page.number != 1 %}hidden{% endif %}>
                        {% for data in page %}
                            <tr style="cursor: pointer;">
                                {% if page.has_previous %}
                                    {% widthratio 10 1 page.previous_page_number as count %}
                                    <td>{{forloop.counter|add:count}}</td>
                                {% else %}
                                    <td>{{forloop.counter}}</td>
                                {% endif %}
                                <td>{{data.pet}}</td>
                                <td>{{data.date}} {{data.time}}</td>
                                <td>{{data.type}}</td>
                                <td>{{data.staff}}</td>
                                <td>
                                    <span>
                                        <i class="{% if data.is_completed %}fa fa-check{% else %}fa fa-xmark{% endif %}" style="color: {% if data.is_completed %}green{% else %}red{% endif %}"></i>
                                    </span>
                                </td>
                                <td>
                                    {% url 'vcmsapp:view-history' customer_id=customer.id appointment_id=data.id as url %}
                                    {% include 'components/icon-button.html' with anchor=True url=url icon='fa fa-eye' title='View Medical Notes' %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                {% endfor %}
        </table>
        {% include 'components/pagination.html' with pages=pages %}
    </div>
</div>

{% endblock %}

vcms/vcmsapp/templates/customer/Pet.html
{% extends 'Base.html' %}

{% block title %}Pets | {{customer.name}}{% endblock %}

{% block content %}
<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                Pets
            </h1>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            {% url 'vcmsapp:add-pet' customer_id=customer.id as url %}
            {% include 'components/anchor-button.html' with url=url text="Add Pet" %}
        </div>
    </div>
    {% if query %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" query=query %}
    {% else %}
        {% include 'components/search.html' with placeholder="Search by Pet Name" search_width_col="5" %}
    {% endif %}    
    <div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Pet Name</th>
                    <th>Animal</th>
                    <th>Species</th>
                    <th>Gender</th>
                    <th>Description</th>
                    <th>View</th>
                </tr>
            </thead>
            {% for page in pages %}
                <tbody id="body{{page.number}}" {% if page.number != 1 %}hidden{% endif %}>
                    {% for data in page %}
                        <tr>
                            {% if page.has_previous %}
                                {% widthratio 10 1 page.previous_page_number as count %}
                                <td>{{forloop.counter|add:count}}</td>
                            {% else %}
                                <td>{{forloop.counter}}</td>
                            {% endif %}
                            <td>{{data.name}}</td>
                            <td>{{data.animal}}</td>
                            <td>{{data.species}}</td>
                            <td>{{data.gender}}</td>
                            <td style="display: flex;">
                                <div class="dropdown">
                                    {{data.description|truncatechars:15}}
                                    {% include 'components/icon-button.html' with icon='fa fa-caret-down' type='button' name='desc_'|add:data.id id='desc_'|add:data.id title='View Description' dropdown=True %}
                                    <div class="dropdown-menu dropdown-menu-end">
                                        <p class="mx-1 my-1">{{data.description}}</p>
                                    </div>
                                </div>
                            </td>
                            <td>
                                {% url 'vcmsapp:view-pet' customer_id=customer.id pet_id=data.id as url %}
                                {% include 'components/icon-button.html' with anchor=True url=url icon='fa fa-eye' title='View Pet' %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            {% endfor %}
        </table>
        {% include 'components/pagination.html' with pages=pages %}
    </div>
</div>

{% endblock %}

vcms/vcmsapp/templates/customer/ViewHistory.html
{% extends 'Base.html' %}

{% block title %}View History | {{appointment.pet.name}} at {{appointment.ssm.slot.start_time}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto; display: flex;">
        <div class="col-9">
            <h1 style="font-weight: bold;">
                Appointment at {{appointment.sssm.ssm.slot.start_time}} for {{appointment.pet.name}}
            </h1>
        </div>
    </div>
    <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        {% include 'details/ViewHistoryDetails.html' %}
    </div>
</div>
<div class="row pb-3" style="display: flex; align-items: center; justify-content: center; margin-left: auto;">
    <div class="col-4">
        {% url 'vcmsapp:history' customer_id=customer.id as url %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
</div>
{% endblock %}

vcms/vcmsapp/templates/customer/ViewPet.html
{% extends 'Base.html' %}

{% block title %}View Pet | {{pet.name}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            {{pet.name}}
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="form-container">
            {% include 'details/ViewPetDetails.html' %}
            {% if image %}
                {% url 'vcmsapp:delete-pet-image' customer_id=customer.id pet_id=pet.id as url %}
                {% include 'components/img.html' with image_url=image delete_url=url disabled=True %}
            {% else %}
                {% url 'vcmsapp:upload-pet-image' customer_id=customer.id as upload_url %}
                {% url 'vcmsapp:remove-pet-image' customer_id=customer.id as remove_url %}
                {% include 'components/dropzone.html' with upload_url=upload_url remove_url=remove_url disabled=True image_for=pet.name %}
            {% endif %}
        </div>
    </div>
</div>
{% url 'vcmsapp:pet' customer_id=customer.id as url %}
{% include 'components/edit-detail-buttons.html' with form_id='editPetForm' url=url %}
{% endblock %}