vcms/vcms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(("vcmsapp.urls", "vcmsapp"), namespace="vcmsapp")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vcms/vcmsapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name='login'),
    path('logout', Logout, name='logout'),
    path('register', Register, name='register'),
    path('return', previous_page, name='return'),
    path('customer/<int:customer_id>/Profile', Profile, name='profile-customer'),
    path('staff/<int:staff_id>/Profile', Profile, name='profile-staff'),
    path('customer/<int:customer_id>/change-password', ChangePassword, name='change-password-customer'),
    path('staff/<int:staff_id>/change-password', ChangePassword, name='change-password-staff'),
    path('terminate-account/<int:customer_id>', TerminateAccount, name='terminate-account'),
    path('customer/<int:customer_id>/Notifications', NotificationPage, name='notification-customer'),
    path('staff/<int:staff_id>/Notifications', NotificationPage, name='notification-staff'),
    path('clear-notifications/<int:customer_id>', ClearNotification, name='clear-notification-customer'),
    path('clear-notifications/<int:staff_id>', ClearNotification, name='clear-notification-staff'),
    path('notification-redirect/<int:notification_id>', NotificationRedirect, name='notification-redirect'),
    path('customer/<int:customer_id>/Appointments', CustomerPage, name='customer'),
    path('staff/<int:staff_id>/Appointments', StaffPage, name='staff'),
    path('staff/<int:staff_id>/make-appointment', MakeAppointmentStaff, name='make-appointment-staff'),
    path('medical-notes/<int:appointment_id>', MedicalNotes, name='medical-notes'),
    path('staff/<int:staff_id>/Slots', SlotPage, name='slot'),
    path('staff/<int:staff_id>/view-slot', ViewSlot, name='view-slot'),
    path('staff/<int:staff_id>/view-event', ViewEvent, name='view-event'),
    path('staff/<int:staff_id>/remove-slot/<int:slot_id>', RemoveSlot, name='remove-slot'),
    path('staff/<int:staff_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-staff'),
    path('staff/<int:staff_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-staff'),
    path('accept-reject-changes', AcceptRejectChanges, name='accept-reject-changes'),
    path('customer/<int:customer_id>/make-appointment', MakeAppointmentCustomer, name='make-appointment-customer'),
    path('customer/<int:customer_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-customer'),
    path('customer/<int:customer_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-customer'),
    path('customer/<int:customer_id>/History', HistoryPage, name='history'),
    path('customer/<int:customer_id>/view-history/<int:appointment_id>', ViewHistory, name='view-history'),
    path('customer/<int:customer_id>/Pets', PetPage, name='pet'),
    path('customer/<int:customer_id>/add-pet', AddPet, name='add-pet'),
    path('upload-pet-image/<int:customer_id>', UploadPetImage, name='upload-pet-image'),
    path('remove-pet-image/<int:customer_id>', RemovePetImage, name='remove-pet-image'),
    path('customer/<int:customer_id>/view-pet/<int:pet_id>', ViewPet, name='view-pet'),
    path('delete-pet-image/<int:customer_id>/<int:pet_id>', DeletePetImage, name='delete-pet-image'),
    path('Adopt-a-Pet', AdoptPage, name='adopt'),
    path('Adopt-a-Pet/view-animal/<int:pet_id>', ViewAdopt, name='view-adopt'),
    path('Adopt-a-Pet/register-animal', RegisterAdopt, name='register-adopt'),
    path('upload-adopt-image', UploadAdoptImage, name='upload-adopt-image'),
    path('remove-adopt-image', RemoveAdoptImage, name='remove-adopt-image'),
    path('delete-adopt-image/<int:pet_id>', DeleteAdoptImage, name='delete-adopt-image'),
    path('admin/<int:admin_id>/Staff', AdminPage, name='admin'),
    path('admin/<int:admin_id>/register-staff', RegisterStaff, name='register-staff'),
    path('admin/<int:admin_id>/view-staff/<str:staff_no>', ViewStaff, name='view-staff'),
    path('admin/<int:admin_id>/approve-customer', ApproveCustomer, name='approve-customer'),

    # JS query endpoints
    path('get-slots-staff', get_slots_staff, name='get-slots-staff'),
    path('get-slots-customer', get_slots_customer, name='get-slots-customer'),
    path('get-pets', get_pets, name='get-pets'),
]

vcms/vcmsapp/views.py
from datetime import datetime
import json
import os
import random
import shutil
from urllib.parse import urlparse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core import serializers
from django.db import transaction
from django.db.models import Q
from sequences import *

from .blockchain import Blockchain
from .models import *
from .utils import *

# Create your views here.
def Home(request):
    return render(request, "Home.html")

# Login and Register
def Login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            if user.role == 'Customer' and not user.is_staff: # validate both role and is_staff fields
                customer = Customer.objects.get(user=user)
                if not customer.is_approved:
                    messages.error(request, "Your account has not been approved yet!")
                    return redirect('vcmsapp:login')
                return redirect('vcmsapp:customer', customer_id=customer.id)
            elif user.role == 'Staff' and user.is_staff:
                if user.is_superuser:
                    admin = Staff.objects.get(user=user)
                    return redirect('vcmsapp:admin', admin_id=admin.id)
                else:
                    staff = Staff.objects.get(user=user)
                    return redirect('vcmsapp:staff', staff_id=staff.id)
            else:
                messages.error(request, "User data error!")
                return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid email or password!")
            return redirect('vcmsapp:login')
    return render(request, "Login.html")

def Register(request):
    if request.method == "POST":
        name        = request.POST['name']
        gender      = request.POST['gender']
        dob         = request.POST['dob'] # date type input default format = 'YYYY-MM-dd'
        phone       = request.POST['phone']
        address     = request.POST['address']
        email       = request.POST['email']
        password    = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists!")
            return redirect('vcmsapp:register')
        elif Customer.objects.filter(phone=phone).exists():
            messages.error(request, "Phone number already exists!")
            return redirect('vcmsapp:register')

        new_user = AddEntity(
            request, User, None,
            email=email,
            password=password,
            role=User.Role.C
        )

        AddEntity(
            request, Customer, None,
            user=new_user,
            name=name,
            gender=gender,
            dob=dob,
            phone=phone,
            address=address,
            is_approved=False
        )

        messages.success(request, 'Registration successful! Please wait for email of approval which would be sent to ' + email + '.')
        return redirect('vcmsapp:login')
    return render(request, "Register.html")

def Logout(request):
    logout(request)
    return redirect('vcmsapp:login')

def previous_page(request):
    previous_page = request.session.get('previous_page', None)
    return redirect(previous_page) if previous_page else redirect('vcmsapp:logout')

@login_required
def Profile(request, staff_id=None, customer_id=None): # staff includes admin
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    if staff_id:
        staff = Staff.objects.get(id=staff_id)
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)

    user = request.user

    disallowed_pages = [
        'change-password',
        'Adopt-a-Pet',
        'Profile',
    ]

    referrer = request.META.get('HTTP_REFERER', None)
    if referrer:
        parsed_url = urlparse(referrer)
        if parsed_url.path not in disallowed_pages and parsed_url.path != '/':
            request.session['previous_page'] = referrer

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newRole = request.POST['role']
                
            EditEntity(
                request, Staff, staff.id, None,
                name=newName,
                gender=newGender,
                role=newRole,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-staff', staff_id=staff_id)
        context['staff'] = staff

    elif customer_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newDob = request.POST['dob']
            newPhone = request.POST['phone']
            newAddress = request.POST['address']

            if customer.phone != newPhone and Customer.objects.filter(phone=newPhone).exists():
                messages.error(request, "Phone number already exists!")
                return redirect('vcmsapp:profile-customer', customer_id=customer_id)

            EditEntity(
                request, Customer, customer.id, None,
                name=newName,
                gender=newGender,
                dob=newDob,
                phone=newPhone,
                address=newAddress,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-customer', customer_id=customer_id)
        context['customer'] = customer
    return render(request, "Profile.html", context)

@login_required
def ChangePassword(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        old_password = request.POST['password']
        new_password = request.POST['newPassword']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password changed successfully!")
            return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid current password!")
            return redirect('vcmsapp:change-password-staff', staff_id=staff_id) if staff_id else redirect('vcmsapp:change-password-customer', customer_id=customer_id)

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "ChangePassword.html", context)

@login_required
def TerminateAccount(request, customer_id):
    to_terminate = Customer.objects.get(id=customer_id)
    if request.method == "POST":
        DeleteEntity(
            request, User, to_terminate.user.id, None
        )

        DeleteEntity(
            request, Customer, to_terminate.id, None
        )
        messages.success(request, "Account terminated successfully!")
        return redirect('vcmsapp:logout')

@login_required
def NotificationPage(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    notifications = Notification.objects.filter(user=user)
    if notifications:
        notifications = serialize_and_paginate(
            notifications, 9            
        )
    else:
        notifications = None

    context = {
        'onPage': 'Notifications',
        'pages': notifications
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "Notification.html", context)

def NotificationRedirect(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    modules = {
        'AppointmentBooked': redirect_view_appointment_staff,
        'AppointmentMade': redirect_view_appointment_customer,
        'AppointmentEditedStaff': redirect_view_appointment_staff,
        'AppointmentEditedCustomer': redirect_view_appointment_customer,
        'AppointmentUpcoming': redirect_view_appointment_customer,
    }

    if notification:
        redirect_func = modules.get(notification.module, None)
        if redirect_func:
            return redirect_func(**notification.data)


def ClearNotification(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        notifications = Notification.objects.filter(user=user)
        for notification in notifications:
            DeleteEntity(
                request, Notification, notification.id, None
            )

        if staff_id:
            staff = Staff.objects.get(id=staff_id)
            return redirect('vcmsapp:notification-staff', staff_id=staff.id)
        elif customer_id:
            customer = Customer.objects.get(id=customer_id)
            return redirect('vcmsapp:notification-customer', customer_id=customer.id)

# Staff
@login_required
def StaffPage(request, staff_id):
    user = request.user

vcms/vcmsapp/templates/forms/AddPetForm.html
{% extends 'FormBase.html' %}

{% block width %}100%{% endblock %}

{% block id %}addPetForm{% endblock %}

{% block action %}{% url 'vcmsapp:add-pet' customer_id=customer.id %}{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='bi bi-alphabet' id='name' name='name' type='text' placeholder='Name' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-paw' id='animal' name='animal' type='text' placeholder='Animal' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-dna' id='species' name='species' type='text' placeholder='Species' value='' required=True %}
    {% with options='<option selected disabled hidden value="">Gender</option><option value="Male">Male</option><option value="Female">Female</option>' %}
        {% include 'components/input.html' with icon='fa fa-venus-mars' type='select' id='gender' name='gender' required=True %}
    {% endwith %}
    {% include 'components/input.html' with icon='fa fa-pen-nib' id='description' name='description' type='textarea' placeholder='Description' %}
    {% include 'components/input.html' with type='hidden' id='filename' name='filename' %}
{% endblock %}

vcms/vcmsapp/templates/forms/AddSlotForm.html
{% extends 'FormBase.html' %}

{% load static %}

{% block width %}100%{% endblock %}

{% block id %}addSlotForm{% endblock %}

{% block action %}{% url 'vcmsapp:add-slot' staff_id=staff.id %}{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='fa fa-hourglass-start' id='start_time' name='start_time' type='time' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-hourglass-end' id='end_time' name='end_time' type='time' value='' required=True %}
    {% include 'components/input.html' with icon='bi bi-clipboard2-pulse' id='type' name='type' type='select' dynamic=True options=types required=True onLoadText='Select Appointment Type' %}
    <script src="{% static 'js/field_validators.js' %}"></script>
    <script>
        validate_time();
    </script>
{% endblock %}

vcms/vcmsapp/templates/forms/ChangePasswordForm.html
{% extends 'FormBase.html' %}

{% load static %}

{% block width %}100%{% endblock %}

{% block id %}addSlotForm{% endblock %}

{% block action %}{% url 'vcmsapp:add-slot' staff_id=staff.id %}{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='fa fa-lock' type='password' id='password' name='password' placeholder='Password' value='' required=True icon_id='eye' %}
    {% include 'components/input.html' with icon='fa fa-lock' type='password' id='newPassword' name='newPassword' placeholder='New Password' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-lock' type='password' id='confirmPassword' name='confirmPassword' placeholder='Confirm Password' value='' required=True %}

    <script src="{% static 'js/field_validators.js' %}"></script>
    <script>
        const show = document.getElementById('show');
        if (show) {
            show.addEventListener('click', (e) => {
                e.preventDefault();

                const eye = document.getElementById('eye');
                if (password.type === 'password') {
                    password.type = 'text';
                    confirmPassword.type = 'text';
                    eye.classList.remove('fa-eye');
                    eye.classList.add('fa-eye-slash');
                    show.title = 'Hide Password';
                } else {
                    password.type = 'password';
                    confirmPassword.type = 'password';
                    eye.classList.remove('fa-eye-slash');
                    eye.classList.add('fa-eye');
                    show.title = 'Show Password';
                }
            });
        }

        validate_password(id='newPassword');
    </script>
{% endblock %}

vcms/vcmsapp/templates/forms/MakeAppointmentForm.html
{% extends 'FormBase.html' %}

{% block width %}100%{% endblock %}

{% block id %}makeAppointmentForm{% endblock %}

{% block action %}{% if form == 'customer' %}{% url 'vcmsapp:make-appointment-customer' customer_id=customer.id %}{% elif form == 'staff' %}{% url 'vcmsapp:make-appointment-staff' staff_id=staff.id %}{% endif %}{% endblock %}

{% block content %}
    {% if form == 'customer' %}
        {% include 'components/input.html' with icon='fa fa-paw' id='pet' name='pet' type='select' dynamic=True options=pets required=True onLoadText='Select Pet' %}
        {% include 'components/input.html' with icon='bi bi-clipboard2-pulse' id='type' name='type' type='select' dynamic=True options=types required=True onLoadText='Select Appointment Type' %}
        {% include 'components/input.html' with icon='fa fa-stethoscope' id='staff' name='staff' type='select' dynamic=True options=staff required=True onLoadText='Select Doctor/Groomer' %}
        {% include 'components/input.html' with icon='fa fa-calendar' id='date' name='date' type='date' value='' required=True onLoadText='Select Date' %}
        {% include 'components/input.html' with icon='fa fa-clock' id='time' name='time' type='select' dynamic=True options=slots required=True onLoadText='Select Time' %}
        {% include 'components/input.html' with icon='fa fa-comment-medical' id='description' name='description' type='textarea' placeholder='Description' %}
        <script>
            $(document).ready(function() {
                function fetchSlots() {
                    var type = $('#type').val();
                    var date = $('#date').val();
                    var staff = $('#staff').val();
                    
                    var timeSelect = $('#time');
                    timeSelect.empty();
                    timeSelect.append($('<option></option>').attr('value', '').text('Select Time').prop('hidden', true).prop('selected', true).prop('disabled', true));

                    if (!type && (staff || date)) {
                        toastr.error('Please select a type first');
                        return;
                    }

                    if (type && !staff && date) {
                        toastr.error('Please select a staff first');
                        return;
                    }

                    if (type && date && staff) {
                        $.ajax({
                            url: '{% url "vcmsapp:get-slots-customer" %}',
                            method: 'POST',
                            data: {
                                'csrfmiddlewaretoken': '{{csrf_token}}',
                                'type': type,
                                'date': date,
                                'staff': staff
                            },
                            dataType: 'json',
                            success: function(data) {
                                timeSelect.append($('<option></option>').attr('value', '').text('Select Time').prop('hidden', true).prop('selected', true).prop('disabled', true));
                                $.each(data.slots, function(key, value) {
                                    timeSelect.append($('<option></option>').attr('value', value.id).text(value.time));
                                    console.log(value.time);
                                });
                            }
                        });
                    }
                }

                $('#type, #date, #staff').change(fetchSlots);
            });

            const type = document.getElementById('type'); // error because js doesn't recognise django tags
            const staff = document.getElementById('staff');
            const date = document.getElementById('date');
            const time = document.getElementById('time');

            time.addEventListener('click', function() {
                if (type.value === ''){
                    toastr.error('Please select an appointment type first');
                } else if (staff.value === '') {
                    toastr.error('Please select a doctor/groomer first');
                } else if (date.value === ''){
                    toastr.error('Please select a date first');
                }
            });
        </script>
    {% elif form == 'staff' %}
        {% include 'components/input.html' with icon='fa fa-user' id='customer' name='customer' type='select' dynamic=True options=customers required=True onLoadText='Select Customer' %}
        {% include 'components/input.html' with icon='fa fa-paw' id='pet' name='pet' type='select' dynamic=True options=pets required=True onLoadText='Select Pet' %}
        {% include 'components/input.html' with icon='bi bi-clipboard2-pulse' id='type' name='type' type='select' dynamic=True options=types required=True onLoadText='Select Appointment Type' %}
        {% include 'components/input.html' with icon='fa fa-calendar' id='date' name='date' type='date' value='' required=True onLoadText='Select Date' %}
        {% include 'components/input.html' with icon='fa fa-clock' id='time' name='time' type='select' dynamic=True options=slots required=True onLoadText='Select Time' %}
        {% include 'components/input.html' with icon='fa fa-comment-medical' id='description' name='description' type='textarea' rows='4' placeholder='Description' %}

        <script>
            $(document).ready(function() {
                $('#customer').change(function() {
                    var customerData = $(this).val();
                    $.ajax({
                        url: '{% url "vcmsapp:get-pets" %}',
                        method: 'POST',
                        data: {
                            'csrfmiddlewaretoken': '{{csrf_token}}',
                            'customer_data': customerData
                        },
                        dataType: 'json',
                        success: function(data) {
                            var petSelect = $('#pet');
                            petSelect.empty();
                            petSelect.append($('<option></option>').attr('value', '').text('Select Pet').prop('hidden', true).prop('selected', true).prop('disabled', true));
                            $.each(data.pets, function(key, value) {
                                petSelect.append($('<option></option>').attr('value', value.id).text(value.name));
                            });
                        }
                    });
                });
                function fetchSlots() {
                    var type = $('#type').val();
                    var date = $('#date').val();
                    
                    var timeSelect = $('#time');
                    timeSelect.empty();
                    timeSelect.append($('<option></option>').attr('value', '').text('Select Time').prop('hidden', true).prop('selected', true).prop('disabled', true));

                    if (!type && date) {
                        toastr.error('Please select a type first');
                        return;
                    }

                    if (type && date) {
                        $.ajax({
                            url: '{% url "vcmsapp:get-slots-staff" %}',
                            method: 'POST',
                            data: {
                                'csrfmiddlewaretoken': '{{csrf_token}}',
                                'type': type,
                                'date': date
                            },
                            dataType: 'json',
                            success: function(data) {
                                timeSelect.append($('<option></option>').attr('value', '').text('Select Time').prop('hidden', true).prop('selected', true).prop('disabled', true));
                                $.each(data.slots, function(key, value) {
                                    timeSelect.append($('<option></option>').attr('value', value.id).text(value.time));
                                });
                            }
                        });
                    }
                }

                $('#type, #date').change(fetchSlots);
            });

            const customer = document.getElementById('customer');
            const pet = document.getElementById('pet');
            const time = document.getElementById('time');

            pet.addEventListener('click', function() {
                if (customer.value === ''){
                    toastr.error('Please select a customer first');
                }
            })

            time.addEventListener('click', function() {
                if (type.value === ''){
                    toastr.error('Please select an appointment type first');
                } else if (date.value === ''){
                    toastr.error('Please select a date first');
                }
            });
        </script>
    {% endif %}
{% endblock %}

<!-- pet /-->
<!-- appointment date /-->
<!-- appointment time /-->
<!-- appointment type /-->
<!-- doctor/groomer depending on the appointment type /-->

vcms/vcmsapp/templates/forms/MedicalNotesForm.html
{% extends 'FormBase.html' %}

{% block width %}100%{% endblock %}

{% block id %}medicalNotesForm{% endblock %}

{% block action %}{% url 'vcmsapp:medical-notes' appointment_id=appointment.id %}{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='fa fa-file-prescription' id='notes' name='notes' placeholder='Notes' type='textarea' rows='8' required=True %}
    {% include 'components/input.html' with icon='fa fa-pills' id='prescription' name='prescription' placeholder='Prescription' type='textarea' rows='8' required=True %}

    <script>

    </script>
{% endblock %}

vcms/vcmsapp/templates/forms/RegisterAdoptForm.html
{% extends 'FormBase.html' %}

{% block width %}100%{% endblock %}

{% block id %}registerAdoptForm{% endblock %}

{% block action %}{% url 'vcmsapp:register-adopt' %}{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='bi bi-alphabet' id='name' name='name' type='text' placeholder='Name' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-paw' id='animal' name='animal' type='text' placeholder='Animal' value='' required=True %}
    {% include 'components/input.html' with icon='fa fa-dna' id='species' name='species' type='text' placeholder='Species' value='' required=True %}
    {% with options='<option selected disabled hidden value="">Gender</option><option value="Male">Male</option><option value="Female">Female</option>' %}
        {% include 'components/input.html' with icon='fa fa-venus-mars' type='select' id='gender' name='gender' required=True %}
    {% endwith %}
    {% include 'components/input.html' with icon='fa fa-pen-nib' id='description' name='description' type='textarea' placeholder='Description' %}
    {% include 'components/input.html' with type='hidden' id='filename' name='filename' %}
{% endblock %}

vcms/vcmsapp/templates/forms/RegisterStaffForm.html
{% extends 'FormBase.html' %}

{% load static %}

{% block width %}100%{% endblock %}

{% block id %}registerStaffForm{% endblock %}

{% block content %}
    {% include 'components/input.html' with icon='fa fa-user-tie' id='generatedStaffNo' name='generatedStaffNo' type='text' value=next_staff_no disabled=True %}
    {% include 'components/input.html' with icon='bi bi-alphabet' id='name' name='name' type='text' placeholder='Name' required=True %}
    {% with options='<option selected disabled hidden value="">Gender</option><option value="Male">Male</option><option value="Female">Female</option>' %}
        {% include 'components/input.html' with icon='fa fa-venus-mars' type='select' id='gender' name='gender' required=True %}
    {% endwith %}
    {% with options='<option selected disabled hidden value="">Role</option><option value="Doctor">Doctor</option><option value="Groomer">Groomer</option>' %}
        {% include 'components/input.html' with icon='fa fa-id-badge' id='role' name='role' type='select' required=True %}
    {% endwith %}
    {% include 'components/input.html' with icon='fa fa-envelope' id='email' name='email' type='email' placeholder='Email' required=True %}
    {% include 'components/input.html' with icon='fa fa-lock' id='generatedPassword' name='generatedPassword' type='text' value=next_staff_password disabled=True %}
    {% include 'components/input.html' with type='hidden' id='password' name='password' value=next_staff_password %}
    {% include 'components/input.html' with type='hidden' id='staff_no' name='staff_no' value=next_staff_no %}

    <script src="{% static 'js/field_validators.js' %}"></script>
    <script>
        validate_name();
    </script>
{% endblock %}