vcms/vcms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(("vcmsapp.urls", "vcmsapp"), namespace="vcmsapp")),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vcms/vcmsapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Login, name='login'),
    path('logout', Logout, name='logout'),
    path('register', Register, name='register'),
    path('return', previous_page, name='return'),
    path('customer/<int:customer_id>/Profile', Profile, name='profile-customer'),
    path('staff/<int:staff_id>/Profile', Profile, name='profile-staff'),
    path('customer/<int:customer_id>/change-password', ChangePassword, name='change-password-customer'),
    path('staff/<int:staff_id>/change-password', ChangePassword, name='change-password-staff'),
    path('terminate-account/<int:customer_id>', TerminateAccount, name='terminate-account'),
    path('customer/<int:customer_id>/Notifications', NotificationPage, name='notification-customer'),
    path('staff/<int:staff_id>/Notifications', NotificationPage, name='notification-staff'),
    path('clear-notifications/<int:customer_id>', ClearNotification, name='clear-notification-customer'),
    path('clear-notifications/<int:staff_id>', ClearNotification, name='clear-notification-staff'),
    path('notification-redirect/<int:notification_id>', NotificationRedirect, name='notification-redirect'),
    path('customer/<int:customer_id>/Appointments', CustomerPage, name='customer'),
    path('staff/<int:staff_id>/Appointments', StaffPage, name='staff'),
    path('staff/<int:staff_id>/make-appointment', MakeAppointmentStaff, name='make-appointment-staff'),
    path('medical-notes/<int:appointment_id>', MedicalNotes, name='medical-notes'),
    path('staff/<int:staff_id>/Slots', SlotPage, name='slot'),
    path('staff/<int:staff_id>/view-slot', ViewSlot, name='view-slot'),
    path('staff/<int:staff_id>/view-event', ViewEvent, name='view-event'),
    path('staff/<int:staff_id>/remove-slot/<int:slot_id>', RemoveSlot, name='remove-slot'),
    path('staff/<int:staff_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-staff'),
    path('staff/<int:staff_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-staff'),
    path('accept-reject-changes', AcceptRejectChanges, name='accept-reject-changes'),
    path('customer/<int:customer_id>/make-appointment', MakeAppointmentCustomer, name='make-appointment-customer'),
    path('customer/<int:customer_id>/view-appointment/<int:appointment_id>', ViewAppointment, name='view-appointment-customer'),
    path('customer/<int:customer_id>/cancel-appointment', CancelAppointment, name='cancel-appointment-customer'),
    path('customer/<int:customer_id>/History', HistoryPage, name='history'),
    path('customer/<int:customer_id>/view-history/<int:appointment_id>', ViewHistory, name='view-history'),
    path('customer/<int:customer_id>/Pets', PetPage, name='pet'),
    path('customer/<int:customer_id>/add-pet', AddPet, name='add-pet'),
    path('upload-pet-image/<int:customer_id>', UploadPetImage, name='upload-pet-image'),
    path('remove-pet-image/<int:customer_id>', RemovePetImage, name='remove-pet-image'),
    path('customer/<int:customer_id>/view-pet/<int:pet_id>', ViewPet, name='view-pet'),
    path('delete-pet-image/<int:customer_id>/<int:pet_id>', DeletePetImage, name='delete-pet-image'),
    path('Adopt-a-Pet', AdoptPage, name='adopt'),
    path('Adopt-a-Pet/view-animal/<int:pet_id>', ViewAdopt, name='view-adopt'),
    path('Adopt-a-Pet/register-animal', RegisterAdopt, name='register-adopt'),
    path('upload-adopt-image', UploadAdoptImage, name='upload-adopt-image'),
    path('remove-adopt-image', RemoveAdoptImage, name='remove-adopt-image'),
    path('delete-adopt-image/<int:pet_id>', DeleteAdoptImage, name='delete-adopt-image'),
    path('admin/<int:admin_id>/Staff', AdminPage, name='admin'),
    path('admin/<int:admin_id>/register-staff', RegisterStaff, name='register-staff'),
    path('admin/<int:admin_id>/view-staff/<str:staff_no>', ViewStaff, name='view-staff'),
    path('admin/<int:admin_id>/approve-customer', ApproveCustomer, name='approve-customer'),

    # JS query endpoints
    path('get-slots-staff', get_slots_staff, name='get-slots-staff'),
    path('get-slots-customer', get_slots_customer, name='get-slots-customer'),
    path('get-pets', get_pets, name='get-pets'),
]

vcms/vcmsapp/views.py
from datetime import datetime
import json
import os
import random
import shutil
from urllib.parse import urlparse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core import serializers
from django.db import transaction
from django.db.models import Q
from sequences import *

from .blockchain import Blockchain
from .models import *
from .utils import *

# Create your views here.
def Home(request):
    return render(request, "Home.html")

# Login and Register
def Login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            if user.role == 'Customer' and not user.is_staff: # validate both role and is_staff fields
                customer = Customer.objects.get(user=user)
                if not customer.is_approved:
                    messages.error(request, "Your account has not been approved yet!")
                    return redirect('vcmsapp:login')
                return redirect('vcmsapp:customer', customer_id=customer.id)
            elif user.role == 'Staff' and user.is_staff:
                if user.is_superuser:
                    admin = Staff.objects.get(user=user)
                    return redirect('vcmsapp:admin', admin_id=admin.id)
                else:
                    staff = Staff.objects.get(user=user)
                    return redirect('vcmsapp:staff', staff_id=staff.id)
            else:
                messages.error(request, "User data error!")
                return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid email or password!")
            return redirect('vcmsapp:login')
    return render(request, "Login.html")

def Register(request):
    if request.method == "POST":
        name        = request.POST['name']
        gender      = request.POST['gender']
        dob         = request.POST['dob'] # date type input default format = 'YYYY-MM-dd'
        phone       = request.POST['phone']
        address     = request.POST['address']
        email       = request.POST['email']
        password    = request.POST['password']

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already exists!")
            return redirect('vcmsapp:register')
        elif Customer.objects.filter(phone=phone).exists():
            messages.error(request, "Phone number already exists!")
            return redirect('vcmsapp:register')

        new_user = AddEntity(
            request, User, None,
            email=email,
            password=password,
            role=User.Role.C
        )

        AddEntity(
            request, Customer, None,
            user=new_user,
            name=name,
            gender=gender,
            dob=dob,
            phone=phone,
            address=address,
            is_approved=False
        )

        messages.success(request, 'Registration successful! Please wait for email of approval which would be sent to ' + email + '.')
        return redirect('vcmsapp:login')
    return render(request, "Register.html")

def Logout(request):
    logout(request)
    return redirect('vcmsapp:login')

def previous_page(request):
    previous_page = request.session.get('previous_page', None)
    return redirect(previous_page) if previous_page else redirect('vcmsapp:logout')

@login_required
def Profile(request, staff_id=None, customer_id=None): # staff includes admin
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    if staff_id:
        staff = Staff.objects.get(id=staff_id)
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)

    user = request.user

    disallowed_pages = [
        'change-password',
        'Adopt-a-Pet',
        'Profile',
    ]

    referrer = request.META.get('HTTP_REFERER', None)
    if referrer:
        parsed_url = urlparse(referrer)
        if parsed_url.path not in disallowed_pages and parsed_url.path != '/':
            request.session['previous_page'] = referrer

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newRole = request.POST['role']
                
            EditEntity(
                request, Staff, staff.id, None,
                name=newName,
                gender=newGender,
                role=newRole,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-staff', staff_id=staff_id)
        context['staff'] = staff

    elif customer_id:
        if request.method == "POST":
            newName = request.POST['name']
            newGender = request.POST['gender']
            newDob = request.POST['dob']
            newPhone = request.POST['phone']
            newAddress = request.POST['address']

            if customer.phone != newPhone and Customer.objects.filter(phone=newPhone).exists():
                messages.error(request, "Phone number already exists!")
                return redirect('vcmsapp:profile-customer', customer_id=customer_id)

            EditEntity(
                request, Customer, customer.id, None,
                name=newName,
                gender=newGender,
                dob=newDob,
                phone=newPhone,
                address=newAddress,
            )

            messages.success(request, 'Profile updated successfully!')
            return redirect('vcmsapp:profile-customer', customer_id=customer_id)
        context['customer'] = customer
    return render(request, "Profile.html", context)

@login_required
def ChangePassword(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        old_password = request.POST['password']
        new_password = request.POST['newPassword']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()
            messages.success(request, "Password changed successfully!")
            return redirect('vcmsapp:login')
        else:
            messages.error(request, "Invalid current password!")
            return redirect('vcmsapp:change-password-staff', staff_id=staff_id) if staff_id else redirect('vcmsapp:change-password-customer', customer_id=customer_id)

    context = {
        'onPage': 'Profile',
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "ChangePassword.html", context)

@login_required
def TerminateAccount(request, customer_id):
    to_terminate = Customer.objects.get(id=customer_id)
    if request.method == "POST":
        DeleteEntity(
            request, User, to_terminate.user.id, None
        )

        DeleteEntity(
            request, Customer, to_terminate.id, None
        )
        messages.success(request, "Account terminated successfully!")
        return redirect('vcmsapp:logout')

@login_required
def NotificationPage(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    notifications = Notification.objects.filter(user=user)
    if notifications:
        notifications = serialize_and_paginate(
            notifications, 9            
        )
    else:
        notifications = None

    context = {
        'onPage': 'Notifications',
        'pages': notifications
    }

    if staff_id:
        staff = Staff.objects.get(id=staff_id)
        context['staff'] = staff
    elif customer_id:
        customer = Customer.objects.get(id=customer_id)
        context['customer'] = customer
    return render(request, "Notification.html", context)

def NotificationRedirect(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    modules = {
        'AppointmentBooked': redirect_view_appointment_staff,
        'AppointmentMade': redirect_view_appointment_customer,
        'AppointmentEditedStaff': redirect_view_appointment_staff,
        'AppointmentEditedCustomer': redirect_view_appointment_customer,
        'AppointmentUpcoming': redirect_view_appointment_customer,
    }

    if notification:
        redirect_func = modules.get(notification.module, None)
        if redirect_func:
            return redirect_func(**notification.data)


def ClearNotification(request, staff_id=None, customer_id=None):
    if not staff_id and not customer_id:
        raise ValueError("Either staff_id or customer_id must be provided!")
    user = request.user

    if request.method == "POST":
        notifications = Notification.objects.filter(user=user)
        for notification in notifications:
            DeleteEntity(
                request, Notification, notification.id, None
            )

        if staff_id:
            staff = Staff.objects.get(id=staff_id)
            return redirect('vcmsapp:notification-staff', staff_id=staff.id)
        elif customer_id:
            customer = Customer.objects.get(id=customer_id)
            return redirect('vcmsapp:notification-customer', customer_id=customer.id)

# Staff
@login_required
def StaffPage(request, staff_id):
    user = request.user

vcms/vcmsapp/templates/staff/AddSlot.html
{% extends 'Base.html' %}

{% block title %}Add Slot | {{date}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            Add Slot | {{date}}
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        {% include 'forms/AddSlotForm.html' %}
    </div>
</div>
<div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-3">
        {% url 'vcmsapp:slot' staff_id=staff.id as url %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
    <div class="col-3">
        <button type="submit" style="border-radius: 10px;" id="submitBtn">Add Slot</button>
    </div>
</div>

<script>
    var submitBtn = document.getElementById('submitBtn');
    var form = document.getElementById('addSlotForm');
    
    submitBtn.addEventListener('click', function() {
        if (form.reportValidity()) {
            form.submit();
        }
    });

</script>
{% endblock %}

vcms/vcmsapp/templates/staff/RegisterAdopt.html
{% extends 'Base.html' %}

{% block title %}Register Animal{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <h1 style="font-weight: bold;">
            Register Animal
        </h1>
        <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
    </div>
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="form-container">
            {% include 'forms/RegisterAdoptForm.html' %}
            <br>
            <div class="row">
                <div class="col-1"></div>
                <div class="col-10">
                    <div class="accordion" id="imageUploadAccordion">
                        <div class="card" style="border-color: #E5E5E5;">
                            <div class="card-header" id="imageUploadHeading" style="background-color: #E5E5E5; border-color: transparent;">
                                {% include 'components/input.html' with type='button' value='Upload Animal Image' accordion_id='imageUploadDiv' icon='fa fa-upload' %}
                            </div>
                            <div class="collapse" id="imageUploadDiv" aria-labelledby="imageUploadHeading" data-bs-parent="#imageUploadAccordion">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data" class="dropzone needsclick" id="imageUpload">
                                        {% csrf_token %}
                                        <div class="dz-message needsclick">
                                            <i class="fa fa-upload"></i>
                                            <h6 style="font-size: smaller;">Drop files here or click to upload.</h6>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row pb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-3">
        {% url 'vcmsapp:adopt' as url %}
        {% include 'components/anchor-button.html' with url=url text="Back" %}
    </div>
    <div class="col-3">
        <button type="submit" style="border-radius: 10px;" id="submitBtn">Register Animal</button>
    </div>
</div>
<script>
    Dropzone.autoDiscover = false;

    var imageUpload = new Dropzone("#imageUpload", {
        url: "{% url 'vcmsapp:upload-adopt-image' %}",
        paramName: "imageUpload",
        maxFilesize: 2,
        maxFiles: 1,
        acceptedFiles: ".jpeg,.jpg,.png,.gif",
        addRemoveLinks: true,
        uploadMultiple: false,
        dictRemoveFile: "Remove",
        dictFileTooBig: "Image is larger than 2MB",
        dictMaxFilesExceeded: "Only 1 image is allowed",
        init: function() {
            this.on("success", function(file, response) {
                document.getElementById('filename').value = response.filename;
            });
            this.on("addedfile", function(file) {
                if (this.files.length > 1) {
                    this.removeFile(this.files[0]);
                }
            });
            this.on("removedfile", function(file) {
                $.ajax({
                    url: "{% url 'vcmsapp:remove-adopt-image' %}",
                    type: "POST",
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        filename: file.name
                    },
                    success: function(response) {
                        toastr.success('Image removed successfully');
                    },
                    error: function(response) {
                        toastr.error('Image failed to remove');
                    }
                })

                if (this.files.length === 0) {
                    this.emit("reset");
                }
            });
            this.on("maxfilesexceeded", function(file) {
                this.removeAllFiles();
                this.addFile(file);
            });
        }
    });

    $(document).ready(function(){
        $(".card").hover(
            function(){
                $(this).find('.collapse').collapse('show');
            },
            function(){
                $(this).find('.collapse').collapse('hide');
            }
        )
    })

    var submitBtn = document.getElementById('submitBtn');
    var form = document.getElementById('registerAdoptForm');

    submitBtn.addEventListener('click', function() {
        if (form.checkValidity()) {
            form.submit();
        }
    });
</script>
{% endblock %}

vcms/vcmsapp/templates/staff/Slot.html
{% extends 'Base.html' %}

{% block title %}Slots | {{staff.name}}{% endblock %}

{% block content %}
<style>
    .fc{
        color: black;
    }
    .fc .fc-col-header-cell{
        background-color: #FFE97F;
    }
    .fc .fc-col-header-cell-cushion{
        text-decoration: none;
        color: black;
    }
    .fc .fc-daygrid-day-number{
        text-decoration: none;
        color: black;
    }
    .fc-event{
        cursor: pointer;
    }
    .fc-daygrid-day,
    .fc-daygrid-day .fc-day-today{
        cursor: pointer;
    }
    .fc-daygrid-day:hover,
    .fc-daygrid-day .fc-day-today:hover{
        background-color: #FFD300 !important;
    }
</style>

<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                Slots
            </h1>
        </div>
    </div>  
    <div class="row pb-3" style="height: fit-content; width: 100%; margin-left: auto;">
        <div class="card">
            <div class="card-body">
                <div id="calendar"></div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'dayGridMonth',
            themeSystem: 'bootstrap5',
            headerToolbar: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay'
            },
            events: [
                {% for event in events %} // errors because js doesn't understand django template tags but it's fine
                    {
                        title: '{{event.title}}',
                        start: '{{event.start}}',
                        end: '{{event.end}}',
                        color: '{{event.end}}' < new Date().toISOString() ? 'gray' : '{{event.available}}' == 'True' ? 'green' : 'red',
                    },
                {% endfor %}
            ],
            dateClick: function(info) {
                var clickedDate = new Date(info.dateStr);
                var tomorrow = new Date();
                tomorrow.setDate(tomorrow.getDate() + 1); // Set the date to tomorrow
                tomorrow.setHours(0, 0, 0, 0); // Set the time to 00:00:00.000

                if (clickedDate < tomorrow) {
                    toastr.error("Cannot select a date before tomorrow.");
                } else {
                    var dateUrl = "{% url 'vcmsapp:view-slot' staff_id=staff.id %}" + "?date=" + info.dateStr;
                    window.location.href = dateUrl;
                }
            },
            eventClick: function(info) {
                var start = info.event.start;
                var end = info.event.end;

                var startStr = start.getFullYear() + '-' + (start.getMonth() + 1).toString().padStart(2, '0') + '-' + start.getDate().toString().padStart(2, '0') + 'T' + start.getHours().toString().padStart(2, '0') + ':' + start.getMinutes().toString().padStart(2, '0') + ':' + start.getSeconds().toString().padStart(2, '0');
                var endStr = end.getFullYear() + '-' + (end.getMonth() + 1).toString().padStart(2, '0') + '-' + end.getDate().toString().padStart(2, '0') + 'T' + end.getHours().toString().padStart(2, '0') + ':' + end.getMinutes().toString().padStart(2, '0') + ':' + end.getSeconds().toString().padStart(2, '0');

                var clickedDate = new Date(info.event.start);
                clickedDate.setHours(0, 0, 0, 0); // Set the time to 00:00:00.000

                var tomorrow = new Date();
                tomorrow.setDate(tomorrow.getDate() + 1); // Set the date to tomorrow
                tomorrow.setHours(0, 0, 0, 0);

                if (clickedDate < tomorrow) {
                    toastr.error("Cannot select an event that starts before tomorrow.");
                } else {
                    var eventUrl = "{% url 'vcmsapp:view-event' staff_id=staff.id %}" + "?type=" + info.event.title + "&start=" + startStr + "&end=" + endStr;
                    window.location.href = eventUrl;
                }
            }
        });

        calendar.render();
    });
</script>
{% endblock %}

vcms/vcmsapp/templates/staff/Staff.html
{% extends 'Base.html' %}

{% block title %}Upcoming Appointments | {{staff.name}}{% endblock %}

{% block content %}
<div style="padding: 0%;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-6">
            <h1 style="font-weight: bold;">
                Upcoming Appointments
            </h1>
        </div>
        <div class="col-3"></div>
        <div class="col-3">
            {% url 'vcmsapp:make-appointment-staff' staff_id=staff.id as url %}
            {% include 'components/anchor-button.html' with url=url text="Add Appointment" %}
        </div>
    </div>
    {% if query %}
        {% include 'components/search.html' with placeholder="Search by Customer Name" search_width_col="5" query=query %}
    {% else %}
        {% include 'components/search.html' with placeholder="Search by Customer Name" search_width_col="5" %}
    {% endif %}    
    <div class="row" style="height: fit-content; width: 100%; margin-left: auto;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Pet Name</th>
                    <th>Customer</th>
                    <th>Date & Time</th>
                    <th>Appointment Type</th>
                    <th>View</th>
                </tr>
            </thead>
                {% for page in pages %}
                    <tbody id="body{{page.number}}" {% if page.number != 1 %}hidden{% endif %}>
                        {% for data in page %}
                            <tr style="cursor: pointer;">
                                {% if page.has_previous %}
                                    {% widthratio 10 1 page.previous_page_number as count %}
                                    <td>{{forloop.counter|add:count}}</td>
                                {% else %}
                                    <td>{{forloop.counter}}</td>
                                {% endif %}
                                <td>{{data.pet}}</td>
                                <td>{{data.customer}}</td>
                                <td>{{data.date}} {{data.start_time}} - {{data.end_time}}</td>
                                <td>{{data.type}}</td>
                                <td>
                                    {% url 'vcmsapp:view-appointment-staff' appointment_id=data.id staff_id=staff.id as url %}                                    
                                    {% include 'components/icon-button.html' with anchor=True url=url icon='fa fa-eye' title='View' %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                {% endfor %}
        </table>
        {% include 'components/pagination.html' with pages=pages %}
    </div>
</div>

{% endblock %}

vcms/vcmsapp/templates/staff/ViewEvent.html
{% extends 'Base.html' %}

{% block title %}View Slot | {{date}}{% endblock %}

{% block content %}
<div class="row" style="padding: 0%; height: fit-content;">
    <div class="row mb-3" style="margin-left: auto;">
        <div class="col-10">
            <h1 style="font-weight: bold;">
                View Slot | {{date}}
            </h1>
        </div>
        <div class="col-2">
            {% include 'components/anchor-button.html' with url='#' text="Remove Slot" id='deleteBtn' modal_toggle=True modal_id='removeModal' %}
        </div>
    </div>
    <hr style="border-top: thin solid lightgrey; opacity: 0.2;">
</div>
<div class="row mb-3" style="height: fit-content; width: 100%; margin-left: auto;">
    <div class="col-3"></div>
    <div class="col-6">
        {% include 'details/ViewEventDetails.html' %}
    </div>
</div>
{% url 'vcmsapp:slot' staff_id=staff.id as url %}
{% include 'components/edit-detail-buttons.html' with form_id='editSlotForm' url=url %}

<!-- Modal -->
<div class="modal fade" id="removeModal" tabindex="-1" aria-labelledby="removeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="removeModalLabel">Remove Confirmation</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Are you sure to remove this slot?</h4>
            </div>
            <div class="modal-footer">
                <div class="row" style="width: 100%;">
                    <div style="display: flex; justify-content: center;">
                        <div class="col-5 mx-2">
                            {% include 'components/anchor-button.html' with url='#' text='Back' modal_dismiss=True %}
                        </div>
                        <div class="col-5 mx-2">
                            <form action="{% url 'vcmsapp:remove-slot' staff_id=staff.id slot_id=slot.id %}" method="post" id="removeSlotForm">
                                {% csrf_token %}
                                {% include 'components/input.html' with type='hidden' id='appointment_id' name='appointment_id' value=appointment.id %}
                                {% include 'components/anchor-button.html' with url='#' text='Remove Slot' id='removeSlotBtn' %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var removeBtn = document.getElementById('removeSlotBtn');
    var form = document.getElementById('removeSlotForm');

    removeBtn.addEventListener('click', function() {
        if (form.reportValidity()) {
            form.submit();
        }
    });
</script>
{% endblock %}